"""added models for ScoreCard, Round, and Course

Revision ID: 2f69c83f996e
Revises: 0dc929299ce3
Create Date: 2025-02-14 14:01:14.060122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f69c83f996e'
down_revision = '0dc929299ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crs_yrds', sa.Integer(), nullable=True),
    sa.Column('crs_par', sa.Integer(), nullable=True),
    sa.Column('usr_strokes', sa.Integer(), nullable=True),
    sa.Column('usr_scr_to_par', sa.Integer(), nullable=True),
    sa.Column('putts', sa.Integer(), nullable=True),
    sa.Column('bogey_worse', sa.Integer(), nullable=True),
    sa.Column('bogey', sa.Integer(), nullable=True),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('birdie', sa.Integer(), nullable=True),
    sa.Column('eagle', sa.Integer(), nullable=True),
    sa.Column('hoi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('par_3', sa.Boolean(), nullable=True),
    sa.Column('full_18', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_rounds_course_id_courses')),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], name=op.f('fk_rounds_scorecard_id_scorecards')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rounds_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_table('scorecards')
    # ### end Alembic commands ###
