"""removed yardage column  from scorecard model

Revision ID: bdeaada735ff
Revises: 2f69c83f996e
Create Date: 2025-02-14 19:59:54.439240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdeaada735ff'
down_revision = '2f69c83f996e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scorecards', schema=None) as batch_op:
        batch_op.drop_column('crs_yrds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scorecards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crs_yrds', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
